### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by pavou** [RobIsr/OneMoreRepFitness#1]
If  you would like help with that project consider adding a **Readme.md** file to let us know what you are thinking and expecting about that project.

Pantazis 

*gsc forum got me here

**Comment by RobIsr** [comment]
Sure, thank you for that, I have now added a readme file that breifly describes the project. It is still very much a work in progress, and I am somewhat new to using Github. Thanks for understanding.

/Robert

**Comment by RobIsr** [comment]
Sure, thank you for that, I have now added a readme file that breifly describes the project. It is still very much a work in progress, and I am somewhat new to using Github. Thanks for understanding.

/Robert

**Comment by RobIsr** [comment]
Sure, thank you for that, I have now added a readme file that breifly describes the project. It is still very much a work in progress, and I am somewhat new to using Github. Thanks for understanding.

/Robert

**Comment by pavou** [comment]
No problem. That's the point of gsc, to get familiar with android and tools like github!!

**Comment by Pavou** [comment]
No problem. That's the point of gsc, to get familiar with android and tools like github!!
