### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pavou** [RobIsr/OneMoreRepFitness#2]
For an opensource project to [really be one](https://choosealicense.com/no-license/), a License file is need it.

Check that [link ](https://github.com/blog/1530-choosing-an-open-source-license) and add the License of your choice.

**Comment by RobIsr** [comment]
Yeah, that is pobably a good idea, Should this be added as a simple textfile to the repository? I want to use something that is really open for all.

**Comment by pavou** [comment]
You can press  **Create new file** here in github.   
As file's name write **Licence** and a button saying **choose a licence template** will appear on the right side of your screen.  
In my opinion the best fit is MIT Licence but is your go.

**Comment by RobIsr** [comment]
Thanks, Yea the MIT Licence seemed to be the best!
