### ISSUE TITLE
Layout Responsiveness

### ISSUE THREAD

**Issue by pavou** [RobIsr/OneMoreRepFitness#7]
Hi,
in my nexus 5 the layout does not render right.
I think **Relative Layouts** are to blame.   
Would you like to change the layouts to [Constraint Layout](https://developer.android.com/training/constraint-layout/index.html) ? 
If you need help doing it let me know!!

**Comment by RobIsr** [comment]
Sure! It has actually been on my mind. Feel free to play around with the layout:)
